# Generated by Django 5.1.3 on 2024-11-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_artwork_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='uploaded_at',
        ),
    ]
